name       : composer
version    : 1.8.4
release    : 1
source     :
    - https://github.com/composer/composer/releases/download/1.8.4/composer.phar : 6faf282db067f0f7625a5a1d80f4ecd3228ccc9a0388aec1599824c610d5d4e3
license    : MIT
extract    : no
component  : programming.tools
summary    : Composer helps you declare, manage, and install dependencies of PHP projects.
description: |
    Composer helps you declare, manage, and install dependencies of PHP projects.
builddeps  :
    - php
rundeps    :
    - git
    - php
install    : |
    install -Dm00755 $sources/composer.phar $installdir/usr/bin/composer
