name       : composer
version    : 1.8.4
release    : 2
source     :
    - git|https://github.com/composer/composer.git : 1.8.4
license    : MIT
component  : programming.tools
summary    : Composer helps you declare, manage, and install dependencies of PHP projects.
description: |
    Composer helps you declare, manage, and install dependencies of PHP projects.
networking : yes
builddeps  :
    - composer
    - php
rundeps    :
    - git
    - php
setup      : |
    %patch -p1 < $pkgfiles/0001-add-compile-script-call-to-composer.json.patch
    composer install --no-scripts
build      : |
    composer run-script compile
install    : |
    install -Dm00755 $workdir/composer.phar $installdir/usr/bin/composer
